apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::669651121059:user/githubaction-admin
      username: githubaction-admin
      groups:
        - system:masters