apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-staging
  name: test-staging-deploy
spec:
  selector:
    matchLabels:
      app: test-staging-deploy
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        rollingStartDate: "Tue Aug 26 09:06:38 UTC 2021"
      labels:
        app: test-staging-deploy
    spec:
      containers:
      - name: test-staging-deploy
        image: 669651121059.dkr.ecr.us-east-2.amazonaws.com/docker_nodejs_demo:nodejs_demo_image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000

